### ISSUE TITLE
Browser Freezing

### ISSUE THREAD

**Issue by Cupbox** [lovac42/Blitzkrieg#13]
Hello 
My browser freezes and throws an error when I click on a specific tag with large amount of notes (~48000) as shown in the gif below
![2020-01-29_20-30-31](https://user-images.githubusercontent.com/13769570/73370843-c0857000-42ac-11ea-90f4-4a81d69d5143.gif)

However, clicking a tag with fewer notes (~803) and then clicking the last one works fine

![2020-01-29_20-31-05](https://user-images.githubusercontent.com/13769570/73370844-c0857000-42ac-11ea-9dc2-473fb1d4c37d.gif)

Debug info:
Anki 2.1.20 (23f13a31) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 73, in handler
  File "aqt\browser.py", line 755, in _onSearchActivated
  File "aqt\browser.py", line 766, in search
  File "aqt\browser.py", line 168, in search
  File "aqt\browser.py", line 189, in endReset
  File "aqt\progress.py", line 163, in finish
  File "aqt\progress.py", line 197, in _closeWin
AttributeError: 'NoneType' object has no attribute 'cancel'

**Comment by lovac42** [comment]
Thanks Cupbox, this appears to be cause by double searching from xxx* (asterisk). Large tags end up with the progress bar timing out. https://github.com/lovac42/Blitzkrieg/releases
