### ISSUE TITLE
Broken as of Anki 2.1.24 beta 5

### ISSUE THREAD

**Issue by Cupbox** [lovac42/Blitzkrieg#18]
Hi. Biltzkrieg seems to be broken as of the latest [beta](https://betas.ankiweb.net/#/).
Debug info:
Anki 2.1.24 (0c5f22f4) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-13 09:36:47

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 43, in handler
  File "aqt\browser.py", line 1086, in deferredDisplay
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\564851917\main.py", line 54, in replace_buildTree
    decksTree(self,root)
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\564851917\tree.py", line 177, in decksTree
    rootNode.tooltip="Total: %d decks"%browser.col.decks.count()
AttributeError: 'DeckManager' object has no attribute 'count'

**Comment by lovac42** [comment]
Yeah I was telling myself it's about time something breaks this week. And there it is.

**Comment by Cupbox** [comment]
Thanks for the fix lovac.
