### ISSUE TITLE
Error undoing a deletion (CTRL+Z)

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/Blitzkrieg#19]
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-30 14:25:40

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 992, in onUndo
  File "aqt\gui_hooks.py", line 1872, in __call__
  File "lib\site-packages\anki\hooks.py", line 583, in runHook
  File "D:\Anki\Anki.2.1.data\addons21\564851917\main.py", line 76, in onRevertedState
    tok in browserInstance.sidebarTree.node_state.keys():
AttributeError: 'NoneType' object has no attribute 'sidebarTree'

**Comment by lovac42** [comment]
Thanks, this was already fixed just hadn't uploaded to ankiweb yet.
https://github.com/lovac42/Blitzkrieg/commit/ba8ebb72cb14162e8030c5a0e6827ff95ab9ae48

**Comment by cjdduarte** [comment]
Tanks
