### ISSUE TITLE
.37 failed. And how do I get around.

### ISSUE THREAD

**Issue by 5toliv** [lovac42/Blitzkrieg#25]
Hello, how are you!?
I know that the addon was designed for an earlier version (at least that's what I understood with my google translator english), maybe for this reason it is generating the error below when opening the panel in version .37 (because there was no no other addon installed to generate conflict and I want to believe that I didn’t shit in some configuration).

```
Anki 2.1.37 (6d596c8f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-17 10:21:28

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 52, in handler
  File "aqt\browser.py", line 1066, in deferredDisplay
  File "C:\Users\thereArePyramidsInBosnia\AppData\Roaming\Anki2\addons21\564851917\main.py", line 55, in replace_buildTree
    decksTree(self,root)
  File "C:\Users\thereArePyramidsInBosnia\AppData\Roaming\Anki2\addons21\564851917\tree.py", line 164, in decksTree
    expanded=tree.node_state.get("group").get('deck',True)
AttributeError: 'NewSidebarTreeView' object has no attribute 'node_state'
```

**However**, all Blitzkrieg functions run perfectly when I click on the panel holding the "Shift" key. (At least I haven't noticed any errors yet.)

_Note: The shift key is pressed when clicking on the panel, not when starting the application. I imagined, when using shift on the panel, addons that change characteristics of this part would not be loaded, however the functions worked without the error._

See you! Thanks for the tool! It's too useful!

**Comment by DavyLiucc** [comment]
Thanks LOVAC42, It is a usefull addon that I can't live without it .
Thanks tiagooliveira5n , glad to know we can use it with pressed shift key. this addon is very useful.

**Comment by lovac42** [comment]
@DavyLiucc: Shift key just disables all addons.

The good news is that this addon's features are being integrated into Anki, so future versions will work out of box w/o having to mess around with addons.

**Comment by yuuyins** [comment]
just for reference
- https://github.com/ankitects/anki/pull/900
- https://github.com/ankitects/anki/pull/1079
- https://github.com/ankitects/anki/pull/1264
